remote_theme: pages-themes/tactile
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
 
title: Initiation GIT

description: "Commandes pratiques pour l'utilisation de GIT et GitHub. [Menu](/)"

gem "github-pages", group: :jekyll_plugins
